#!/bin/bash

set -ex

cd "$(dirname "$0")/.."

swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"

moduleinterface generate --spm-module ShareThatTo

